# Final Project - Getting and Cleaning Data.
# G. Mercier
# 2015-06-21

# File: readMergeClean.R
# Assumes data has been loaded using script:
#   downLoadData.R

# Assumes taht the working directory is already set.
#source("setWDir.R")

# Summary:
#
# This script will read the data to create data.frames that will be merged, cleaned,
# and processed into a good (tidy) data.frame that is written out to the file
#   tidyData.csv
# This tidy data file can be read using
#   read.table(file.path(GIT.repo,"tidyData.csv"),header=T)
# for subsequent analysis.
#
# Input: data directory generated by downLoadData.R
#        default: HOME/git/cleanData/data
# Output: tidyData.csv
#
# Example Execution:
#   setwd(file.path(Sys.getenv("HOME"),git,cleanData))
#   source(readMergeClean.R)
#
# Read Step:
# Reads the following files into data.frames
#    training data: X_train.txt                        -> dataTrain
#    test data:     X_test.txt                         -> dataTest
#    subject ids for training data:  subject_train.txt -> subjectsTrain
#    subject ids for test data:      subject_test.txt  -> subjectsTest
#    activity codes for training data:  y_training.txt -> activityTrain 
#    activity codes for test data:      y_test.txt     -> activityTest
#
# Merge Step:
# Merges by appending dataTest to bottom of dataTrain
# Does the same for the subject ids and the activity codes.
# This results in three data.frames with the following dimensions:
#      data            Dimensions: 10299x561
#      subjects        Dimensions: 10299x1
#      activity        Dimensions: 10299x1
#
# An additional merge occurs after the clean step described next.
#
# Clean Step:
# From the merged file (i.e. data) selects columns containg data that
# is either "mean" or "std". Then renames the columns with descriptive names
# as detailed below. This results in a data.frame with dimensions:
#        selectedData     Dimensions: 10299x66
# 
# Converts the data in the activity data.frame into a factor variable with
# descriptive factor levels. The names are detailed below.
#
# Replace the column name in the subjects data.frame with a descriptive name ("subject")
#
# Final Merge Step:
# The subjects, activity, and selectedData data.frames are merged by using cbind.
# This creates a tidyData data.frame with the first column containing the subject
# ids, the second column the activity as a factor with 6 levels, and the remaining
# columns the data:
#        tidyData     Dimensions: 10299x68
# 
# Output is a tidy data file named "tidyData.csv"

print("Starting script: readMergeClear.R")

# Default raw data directory name:
DATA.dir <- "data"

# Read files:
print("Loading files... be patient!")

dataTrain=read.table( file.path(DATA.dir,"train","X_train.txt") )
dataTest =read.table( file.path(DATA.dir,"test","X_test.txt")   )

subjectsTrain=read.table( file.path(DATA.dir,"train","subject_train.txt") )
subjectsTest =read.table( file.path(DATA.dir,"test","subject_test.txt")   )

activityTrain=read.table( file.path(DATA.dir,"train","y_train.txt") )
activityTest =read.table( file.path(DATA.dir,"test","y_test.txt")   )

print("Done!")

# Merging the training and test data sets; Train set on top of Test set.
print("Merging training and test data sets...")
data <- rbind(dataTrain,dataTest)

# -------------------Extracting the necessary data ---------------------------
#     Variable                     Column Name        Descriptive Name
#  from feature.txt                in "data"          in "selectedData"
# =============================================================================
# tBodyAcc-mean()-XYZ              V1:V3             tAcc.avg.XYZ                                 
# tBodyAcc-std()-XYZ               V4:V6             tAcc.std.XYZ                                 
# tGravityAcc-mean()-XYZ           V41:V43           tGravityAcc.avg.XYZ                              
# tGravityAcc-std()-XYZ            V44:V46           tGravityAcc.std.XYZ                              
# tBodyAccJerk-mean()-XYZ          V81:V83           tAccJerk.avg.XYZ                             
# tBodyAccJerk-std()-XYZ           V84:V86           tAccJerk.std.XYZ                             
# tBodyGyro-mean()-XYZ             V121:V123         tGyro.avg.XYZ                                
# tBodyGyro-std()-XYZ              V124:V126         tGyro.std.XYZ                                
# tBodyGyroJerk-mean()-XYZ         V161:V163         tGyroJerk.avg.XYZ                            
# tBodyGyroJerk-std()-XYZ          V164:V166         tGyroJerk.std.XYZ                            
# tBodyAccMag-mean()               V201              tAccMag.avg                                  
# tBodyAccMag-std()                V202              tAccMag.std                                  
# tGravityAccMag-mean()            V214              tGravityAccMag.avg                               
# tGravityAccMag-std()             V215              tGravityAccMag.std                               
# tBodyAccJerkMag-mean()           V227              tAccJerkMag.avg                              
# tBodyAccJerkMag-std()            V228              tAccJerkMag.std                              
# tBodyGyroMag-mean()              V240              tGyroMag.avg                                 
# tBodyGyroMag-std()               V241              tGyroMag.std                                 
# tBodyGyroJerkMag-mean()          V253              tGyroJerkMag.avg                             
# tBodyGyroJerkMag-std()           V254              tGyroJerkMag.std                             
# fBodyAcc-mean()-XYZ              V266:V268         fAcc.avg.XYZ                                 
# fBodyAcc-std()-XYZ               V269:V271         fAcc.std.XYZ                                 
# fBodyAccJerk-mean()-XYZ          V345:V347         fAccJerk.avg.XYZ                             
# fBodyAccJerk-std()-XYZ           V348:V350         fAccJerk.std.XYZ                             
# fBodyGyro-mean()-XYZ             V424:V426         fGyro.avg.XYZ                                
# fBodyGyro-std()-XYZ              V427:V429         fGyro.std.XYZ                                
# fBodyAccMag-mean()               V503              fAccMag.avg                            
# fBodyAccMag-std()                V504              fAccMag.std                            
# fBodyBodyAccJerkMag-mean()       V516              fAccJerkMag.avg                    
# fBodyBodyAccJerkMag-std()        V517              fAccJerkMag.std                    
# fBodyBodyGyroMag-mean()          V529              fGyroMag.avg                       
# fBodyBodyGyroMag-std()           V530              fGyroMag.std                       
# fBodyBodyGyroJerk-mean()         V542              fGyroJerk.avg                      
# fBodyBodyGyroJerk-std()          V543              fGyroJerk.std                      
# ==============================================================================
dataCols <- c(1:3, 4:6, 41:43, 44:46, 81:83, 84:86, 121:123, 124:126, 161:163, 164:166,
              201, 202, 214, 215, 227, 228, 240, 241, 253, 254,
              266:268, 269:271, 345:347, 348:350, 424:426, 427:429,
              503, 504, 516, 517, 529, 530, 542, 543)

descriptiveNames <- c(
"tAcc.avg.X",          "tAcc.avg.Y",       "tAcc.avg.Z",                                 
"tAcc.std.X",          "tAcc.std.Y",       "tAcc.std.Z",                                 
"tGravityAcc.avg.X",   "tGravityAcc.avg.Y","tGravityAcc.avg.Z",                              
"tGravityAcc.std.X",   "tGravityAcc.std.Y","tGravityAcc.std.Z",                              
"tAccJerk.avg.X",      "tAccJerk.avg.Y",   "tAccJerk.avg.Z",                             
"tAccJerk.std.X",      "tAccJerk.std.Y",   "tAccJerk.std.Z",                             
"tGyro.avg.X",         "tGyro.avg.Y",      "tGyro.avg.Z",                                
"tGyro.std.X",         "tGyro.std.Y",      "tGyro.std.Z",                                
"tGyroJerk.avg.X",     "tGyroJerk.avg.Y",  "tGyroJerk.avg.Z",                            
"tGyroJerk.std.X",     "tGyroJerk.std.Y",  "tGyroJerk.std.Z",                            
"tAccMag.avg",         "tAccMag.std",                                  
"tGravityAccMag.avg",  "tGravityAccMag.std",                               
"tAccJerkMag.avg",     "tAccJerkMag.std",                              
"tGyroMag.avg",        "tGyroMag.std",                                 
"tGyroJerkMag.avg",    "tGyroJerkMag.std",                             
"fAcc.avg.X",          "fAcc.avg.Y",       "fAcc.avg.Z",                                 
"fAcc.std.X",          "fAcc.std.Y",       "fAcc.std.Z",                                 
"fAccJerk.avg.X",      "fAccJerk.avg.Y",   "fAccJerk.avg.Z",                             
"fAccJerk.std.X",      "fAccJerk.std.Y",   "fAccJerk.std.Z",                             
"fGyro.avg.X",         "fGyro.avg.Y",      "fGyro.avg.Z",                                
"fGyro.std.X",         "fGyro.std.Y",      "fGyro.std.Z",                                
"fAccMag.avg",         "fAccMag.std",                            
"fAccJerkMag.avg",     "fAccJerkMag.std",                    
"fGyroMag.avg",        "fGyroMag.std",                       
"fGyroJerk.avg",       "fGyroJerk.std")

# Extract the columns into selectedData
print("Extracting data containg mean and standard deviations...")
selectedData <- data[,dataCols]

# Replace the generic column names with the descriptive names
print("Renaming columns to descriptive names...")
names(selectedData) <- descriptiveNames

# Merge the subjects ids
print("Processing subject ids and activity data...")
subjects <- rbind(subjectsTrain,subjectsTest)
# Rename it with a descriptive name
names(subjects) <- c("Subject")

# Merge the activity identifiers
activity <- rbind(activityTrain,activityTest)
# Rename it with a descriptive name
names(activity) <- c("Activity")

# Now convert the integer values in activity$Activity into a factor
# with meaningful levels.
#       Level             Descriptive Name
# ====================================================================
#         1                  Walking
#         2                  Walking_Upstairs
#         3                  Walking_Downstairs
#         4                  Sitting
#         5                  Standing
#         6                  Laying
# ====================================================================
activity$Activity <- factor(activity$Activity)
levels(activity$Activity) <- c("Walking", "Walking_Upstairs", "Walking_Downstairs",
                               "Sitting", "Standing", "Laying")

# Finally put all the info together and write it out
print("Creating final tidy data.frame and writing out into tidyData.csv")
tidyData <- cbind(subjects,activity,selectedData)
write.table(tidyData,file.path(GIT.repo,"tidyData.csv"),row.names=F)

print("Script, readMergeClean.R, successfully completed!")

# Check if we can read it back
# readData <- read.table(file.path(GIT.repo,"tidyData.csv"),header=T)
