# Final Project - Getting and Cleaning Data.
# G. Mercier
# 2015-06-21

# File: tidySummary.R
# Assumes working directory is already set.
# source("setWDir.R")

# Summary:
# This file loads the tidy data (tidyData.csv) generated by the readMergeClean.R script
# and creates a new tidy data.frame that contains summary data (mean values) for all the
# measures in tidyData.csv but grouped based on Subject and Activity.
#
# Input: tidyData.csv
# Output: tidySummary.csv
#
# Dependencies:
# requires the dplyr package

print("Starting script: tidySummary.R")

print("Loading dplyr package...")
gotIt <- require(dplyr)
if (!gotIt){
    stop("Unable to load dplyr package!")
}

print("Reading input data from tidyData.csv.")
inputData <- read.table(file.path(GIT.repo,"tidyData.csv"),header=T)

print("Processing: grouping by Subject and Activity and getting summary...")
bySubjectAndActivity <- group_by(inputData,Subject,Activity)
tidySummary <- summarise_each(bySubjectAndActivity,funs(mean))

print("Saving summary in tidySummary.csv.")
write.table(tidySummary,file.path(GIT.repo,"tidySummary.csv"),row.names=F)

print("Script, tidySummary.R, successfully completed!")
